import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const array=[...Array.from(Array(10).keys())]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Flex vs Grid
        </h1>

        <p className={styles.description}>
        </p>

        <div style={{display: 'flex', flexWrap: 'wrap', background: '#ff000020'}}>
          {
            array.map(a =>
              <div style={{width: 100, height: 50, border: '1px black solid', display: 'flex', justifyContent: 'center', alignItems: 'center', background: '#fff'}}>
                <span style={{fontSize: 16, color: 'red'}}>flex&nbsp;</span>
                <span style={{fontSize: 22, fontWeight: 'bold'}}>{a}</span>
              </div>
            )
          }
        </div>
        <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', width: '100%', background: '#0000ff20'}}>
          {
            array.map(a =>
              <div style={{width: '100%', height: 50, border: '1px black solid', display: 'flex', justifyContent: 'center', alignItems: 'center', background: '#fff'}}>
                <span style={{fontSize: 16, color: 'blue'}}>grid&nbsp;</span>
                <span style={{fontSize: 22, fontWeight: 'bold'}}>{a}</span>
              </div>
            )
          }
        </div>
      </main>

    </div>
  )
}

export default Home
